### ISSUE TITLE
Comparison with Fortran namelists

### ISSUE THREAD

**Issue by milancurcic** [jannisteunissen/config_fortran#1]
I am curious how does config_fortran compare to namelists that are part of the language. From the README.md, I can't see any feature of config_fortran that cannot be handled by standard namelists. Is this re-inventing the namelist or do I miss something?

**Comment by jannisteunissen** [comment]
Good point, I guess I should've made this clear in the README (update: now I've done so). Let me summarize some of the main differences:

Benefits of config_fortran:
1. You can read in (1D) arrays of unknown size
2. Settings have documentation, and you can write "documented" output in text or markdown format
3. If you don't want to use global variables, you have to open and read namelists in each module that requires parameters. I think it's nicer to read in a config_fortran type object once and pass that to the modules
4. You can spread out settings over multiple files, which is convenient for setting up parameter studies (this can be done with namelists, but it's not trivial)
5. Flexibility: although namelist implementations slightly differ, you cannot change them like you can config_fortran. Config_fortran for example allows to write only those settings that have been requested in a program.

Benefits of namelist format:
1. More standard, although not completely the same for different vendors/versions yet
2. Support for array(3) = ... syntax
3. Support for array = 10*'dummy' syntax
(Of course, points 2 & 3 could easily be implemented in config_fortran)

**Comment by milancurcic** [comment]
Wonderful, that clears things up a lot, thanks!

I think adding these key differences in the README.md would be helpful.

**Comment by jannisteunissen** [comment]
Thanks for asking, and I have updated README.md now!
