### ISSUE TITLE
Misleading Error if file doesn't exsits

### ISSUE THREAD

**Issue by MRedies** [jannisteunissen/config_fortran#3]
If i try to open non-exsistant file  (e.g. typos) I get the following error:

```
running: /work/jias12/jias1217/STB/inis/new_atan_0.cfg
 The following error occured in m_config:
 CFG_read_file: io_state =  6  while reading from /work/jias12/jias1217/STB/inis/new_atan_0.cfg at line  538968064
```
I think the line might be uninitialized. Would it be possible to catch io_state 6 and give a clearer message? It seems to defined as "File does not exsits"

http://msg.ucsf.edu/local/programs/IBM_Compilers/Fortran/html/pgs/lr76.htm

**Comment by jannisteunissen** [comment]
You're right, I've now changed the open() statements so that they show Fortran's default error messages, so that it should print something like "Fortran runtime error: File ... does not exists"
